### PR TITLE
On/Off A/B tests

### PR DESCRIPTION
**Pull request by creative-dev-lab**
### Context
Implemented query and logic to support on/off A/B tests.

### What's updated/implemented
- widget A/B test variant i.e. enabled/disabled query implemented
- widgets render/not render logic implemented
- updated split_test_variant of `telemetry`, `dispatch` events, and `identifyOrder` with the selected A/B variant
- minor fixes

### Considerations
Need to test this thoroughly on the connector side as well if it hits and uses this variant properly.

### Release type
- [ ] Patch
- [ ] Minor
- [x] Major

### Peer review
- [x] The feature/changes have been peer reviewed
- [ ] Automated test coverage and correctness have been peer reviewed
- [ ] The test plan has been peer reviewed

### CODE REVIEW

**Comment by creative-dev-lab** [comment]
@michaeldawson need this to be re-reviewed to get approved as well. 🙏

**Comment by johnAirRobe** [comment]
To test this will we do it after it has been merged to main?

**Comment by creative-dev-lab** [comment]
> To test this will we do it after it has been merged to main?

I believe this has been tested already with @michaeldawson.
but let's pair again if we want to test this.

**Comment by johnAirRobe** [comment]
> > To test this will we do it after it has been merged to main?
> 
> I believe this has been tested already with @michaeldawson. but let's pair again if we want to test this.

Okay, that's cool. If Michael was still around I'd be happy to merge it but it'll probably be a good idea for someone else to understand how this was tested. So, yeah, lets pair on testing this.

**Comment by creative-dev-lab** [comment]
> > > To test this will we do it after it has been merged to main?
> > 
> > 
> > I believe this has been tested already with @michaeldawson. but let's pair again if we want to test this.
> 
> Okay, that's cool. If Michael was still around I'd be happy to merge it but it'll probably be a good idea for someone else to understand how this was tested. So, yeah, lets pair on testing this.

Alright! Let's do it.

**Comment by johnAirRobe** [comment]
So I installed it and the widget showed. But when I tried to install it to get it to not show I couldn't, but that doesn't matter as when you installed it it didn't show.

LGTM! 🚀

**Review by johnAirRobe — APPROVED** [review]

**Comment by johnAirRobe** [comment]
How do we disable the A/B testing in the sdk?

**Comment by creative-dev-lab** [comment]
> How do we disable the A/B testing in the sdk?

We cannot disable it on the SDK side now, but we can disable that by returning only `default` variant from the connector.

**Pull request merged**
